# IP-address  hostname  host
192.168.1.1   g_host.local   g_host
192.168.1.2   printer_stupid_piece_of_shit.local   printer_stupid_piece_of_shit
192.168.1.3   nice_igor3.local nice_igor3
192.168.1.4   virus_botnet.local virus_botnet
192.168.1.5   some_other_shit254334.local some_other_shit254334
